// Mocks generated by Mockito 5.0.16 from annotations
// in partirecept/test/loginPage_widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:partirecept/screens/authenticaiton/authViewModel.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [AuthViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthViewModel extends _i1.Mock implements _i2.AuthViewModel {
  MockAuthViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.User?> createAccount() =>
      (super.noSuchMethod(Invocation.method(#createAccount, []),
          returnValue: Future<_i4.User?>.value()) as _i3.Future<_i4.User?>);
  @override
  _i3.Future<_i4.User?> login() =>
      (super.noSuchMethod(Invocation.method(#login, []),
          returnValue: Future<_i4.User?>.value()) as _i3.Future<_i4.User?>);
  @override
  String toString() => super.toString();
}
